version: '3.9'
services:

  server:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - "main_db"
      - "sessions_cache"

  sessions_cache:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --requirepass ${CACHE_PASS}
    # volumes:
    #   - cache:/data

  main_db:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: bluedot
      MYSQL_PASSWORD: ${MAINDB_PASS}
      MYSQL_ROOT_PASSWORD: ${MAINDB_PASS}
      MYSQL_DATABASE: main_DB
    # This will initialize session_DB
    entrypoint: sh -c " echo 'CREATE DATABASE IF NOT EXISTS main_DB; CREATE DATABASE IF NOT EXISTS session_DB;' > /docker-entrypoint-initdb.d/init.sql; /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci "
    volumes:
      - main_db_volume:/var/lib/mysql

  main_db_adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  main_db_volume: #driver:local
