version: '3.9'
services:

  server:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - "main_db"
      - "sessions_cache"

  sessions_cache:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --requirepass ${CACHE_PASS}
    # volumes:
    #   - cache:/data

  main_db:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_PASSWORD: ${MAINDB_PASS}
      MYSQL_ROOT_PASSWORD: ${MAINDB_PASS}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - main_db_volume:/var/lib/mysql

  main_db_adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  main_db_volume: #driver:local
