# @no-cookie-jar

@host = localhost:3001

// Login User
POST http://{{host}}/api/login HTTP/3.0
content-type: application/json; charset=utf-8
    
{
    "email": "Dwight.Mertz@hotmail.com",
    "password": "lafoqiyayepecemo"
}

###

GET http://{{host}}/api/allFriends HTTP/3.0
content-type: application/json; charset=utf-8
cookie: sessionId=jGtKawWDI-UpL8jNAth1aTmYqvQ%3D

###

GET http://{{host}}/api/profileInfo HTTP/3.0
content-type: application/json; charset=utf-8
cookie: sessionId=jGtKawWDI-UpL8jNAth1aTmYqvQ%3D