# @no-cookie-jar

@host = localhost:3001

// Login User
POST http://{{host}}/api/login HTTP/3.0
content-type: application/json; charset=utf-8
    
{
    "email": "Shaina_Kovacek99@gmail.com",
    "password": "gibimowuyuquropexepufi"
}

###

// Access protected resources
GET http://{{host}}/api/allFriends HTTP/3.0
content-type: application/json; charset=utf-8
cookie: sessionId=61vuhElaY4vbDxFvrfAOb4kYW6U%3D
