@host = localhost:3001
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxMjMiLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaGFzaFBhc3MiOiIkMmEkMTAkcWpFUjhod0FyS2VVclozbTlaZ0NoZU55UmlMY0NLT0dMU09BWWYva3VLMHgxaTJnMDQvRS4iLCJleHAiOjE2NjIxMjc2OTJ9.AfH-qfnZm50hxUofLDgoSHp1Jmkiy0cWKcFLTLIXj-8

// Register User
POST http://{{host}}/api/register HTTP/3.0
content-type: application/json
    
{
    "username": "test123",
    "email": "test@gmail.com",
    "password": "0123465789"
}

###

// Activation fail
GET http://{{host}}/api/activate/123456789 HTTP/3.0
content-type: application/json

###

// Activate success
GET http://{{host}}/api/activate/{{token}} HTTP/3.0
content-type: application/json